[FIX] OD-1411, avoid invalid dependencies from base_external_dbsource_mssql
Quatra specific: set module to uninstallable. This triggers the precommit to
remove the pymssql 2.2.8 dependency which does not support Python 3.12 that
Odoo.sh runs.

Fixes

```
pip._internal.exceptions.InstallationError: Could not build wheels for pymssql, which is required to install pyproject.toml-based projects
```

during deploy.

Upstream solution discussed in https://github.com/OCA/server-backend/pull/420